### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by sajjadmurtaza** [joliss/jquery-ui-rails#102]
I have included in my Gemfile

ruby '2.2.3'  
gem 'rails', '3.2.22'  
gem 'jquery-ui-rails', '~> 4.1.2'  

But i'm facing Uncaught TypeError: undefined is not a function error.

and for 

ruby "2.1.5"
gem 'rails', '3.2.13'

Its working great. Kindly guide me.

**Comment by rosenfeld** [comment]
I'd suspect that even without `jquery-ui-rails` you'd have this error. Rails 3 is not supported for a long time and I suspect it may not work on recent Ruby versions.

**Comment by sajjadmurtaza** [comment]
@rosenfeld Now what i have to do?

**Comment by rosenfeld** [comment]
I'd strongly advise you to upgrade to Rails 5 as soon as you can. Until there keep using an older MRI Ruby that works with your current application.
