### ISSUE TITLE
ActionView::Template::Error (couldn't find file 'jquery-ui/datepicker' with type 'application/javascript'

### ISSUE THREAD

**Issue by drummerroma** [joliss/jquery-ui-rails#111]
after update from tag v5.0.5 to v.6.0.0. 
gem 'jquery-ui-rails', :git => 'https://github.com/joliss/jquery-ui-rails', :tag => 'v5.0.5' solved

**Comment by Borzik** [comment]
Hi. Version 6.0 has a different folder structure which is uncompatible with v5.0, please see [documentation on requiring specific modules](https://github.com/joliss/jquery-ui-rails#require-specific-modules). In v6.0 need to require it as `//= require jquery-ui/widgets/datepicker`, not as `//= require jquery-ui/datepicker`
