### ISSUE TITLE
Uncaught ReferenceError: define is not defined(…) in the chrome console

### ISSUE THREAD

**Issue by sadiqmmm** [joliss/jquery-ui-rails#112]
Uncaught ReferenceError: define is not defined(…)
![screenshot from 2016-12-01 18-06-10](https://cloud.githubusercontent.com/assets/672989/20794218/1f579760-b7f1-11e6-9c8b-2dcb499a4b20.png)

core.js file
// This file is deprecated in 1.12.0 to be removed in 1.13

**Comment by joliss** [comment]
This should be fixed in 6.0.1 thanks to @Borzik's fix!
