### ISSUE TITLE
images in production subdirectory problem

### ISSUE THREAD

**Issue by naxels** [joliss/jquery-ui-rails#54]
Thanks for the gem first of all, saved me a lot of time :)

I do have a bug however, in development all images are fine
where in production the images go wrong.

The reason for this is because in production I run in a subdirectory (have to)
the javascripts/stylesheets load perfectly as compiled:
http://www.example.com/app/assets/application-(fingerprint).(js/css)

however the jquery-ui images go wrong:
http://www.examples.com/assets/jquery-ui/ui-icons_888888_256x240-(fingerprint).png

while it should be
http://www.examples.com/app/assets/jquery-ui/ui-icons_888888_256x240-(fingerprint).png

notice the difference in the **/app/** part

when however I manually go to the correct url, the jquery-ui assets are actually there, so no problems there.. only routing.

Thank you for fixing this!

**Comment by thoughtafter** [comment]
I ran into this today and in case anyone comes across this issue like I did:

The easiest fix is to set Rails.application.config.action_controller.relative_url_root in an initializer.

See https://github.com/YaleSTC/shifts/issues/402
