### ISSUE TITLE
Any way to prevent require from including "core" etc again?

### ISSUE THREAD

**Issue by jarodtaylor** [joliss/jquery-ui-rails#66]
We have our application.js manifest with jquery.ui being required and a couple widgets included as well. There are certain parts of the application that we use one off widgets and we want to just include it on that page alone. We will have a page specific javascript file included on that page and add require rules in it for any 'one off' JS files. Example:

application.js may have:

//= require jquery.ui.datepicker

admin_page.js may have:
//= require jquery.ui.sortable

Unfortunately when using this gem I will now have jquery.ui.core jquery.ui.widget, etc. included again (once from the application.js file and again in the admin_page.js file).

**Comment by rosenfeld** [comment]
This is how the Rails Assets Pipeline (sprockets) works. There's nothing we can think of to help you with your requirements. If you have a suggestion on how to change this gem to support your workflow please let us know and I'll reopen this ticket.
