### ISSUE TITLE
Asset compilation issue on Heroku

### ISSUE THREAD

**Issue by kjohnston** [joliss/jquery-ui-rails#9]
Upon adding the gem and deploying to Heroku's Cedar stack, asset compilation fails.  After a few minutes it times out and leaves behind the following tidbits:

```
/app/slug-compiler/lib/utils.rb:65:in `block (2 levels) in spawn': command='/app/slug-compiler/lib/../buildpacks/ruby/bin/compile /tmp/build_28buf55d2o6q2 /app/tmp/repo.git/.cache' exit_status=0 out='' at=timeout elapsed=538.774163722992 (Utils::TimeoutError)
```

...

```
Heroku push rejected, failed to compile Ruby/rails app
```

**Comment by pawneetdev** [comment]
Hi,
I am also facing the same problem. This problem is due to the "nokogiri gem". Nokogiri takes ~ 1 sec in development environment but more than 30 sec in heroku. 
@joliss , unfortunately using jquery-ui-rails gem did not work for me.

**Comment by imtiazwazir** [comment]
+1
