### ISSUE TITLE
@import "jquery-ui";

### ISSUE THREAD

**Issue by djonatanb** [joliss/jquery-ui-rails#91]
Hi, I'm trying to load the css file like this in my admin.scss file. The JS is being loaded correctly but I can't get the css to load properly. What am I missing?

**Comment by djonatanb** [comment]
Worked like this in https://github.com/joliss/jquery-ui-rails/issues/89#issuecomment-70554675

@import "jquery-ui/core";
@import "jquery-ui/datepicker";
@import "jquery-ui/theme";

**Comment by krsyoung** [comment]
Thanks @djonatanb, I was stuck on the same thing.  I went with your fix but still seem to have a couple of things off (might just be my project).  I take it everything is working as expected for you now.

**Comment by djonatanb** [comment]
Yes, it was working ok. Using a datetime picker now
