### ISSUE TITLE
Draggable is not a function, even when application.js contains draggable

### ISSUE THREAD

**Issue by juanpastas** [joliss/jquery-ui-rails#95]
I have this in `application.coffee`:

```
#= require jquery
#= require jquery-ui
```

And when I inspect application.js in development, it has:

```
/*!
 * jQuery UI Draggable 1.11.4
 * http://jqueryui.com
 *
 * Copyright jQuery Foundation and other contributors
 * Released under the MIT license.
 * http://jquery.org/license
 *
 * http://api.jqueryui.com/draggable/
 */
...
```

But when I try:

```
$ ->
	$('div:first').draggable().resizable()
```

I get `Uncaught TypeError: $(...).draggable is not a function`.

My line is on application.js line 299xx, while draggable is at line 16319.

Versions:

```
  * jquery-rails (4.0.4)
  * jquery-ui-rails (5.0.5)

```

Any advice?

**Comment by rosenfeld** [comment]
If you could create a simple sample application reproducing the problem and make it available on Github I can give it a chance and see what's happening.

**Comment by rosenfeld** [comment]
I'm closing this issue due to lack of feedback in over a month. Once you have more information on how to reproduce this please let us know and I'll reopen this ticket.
